nodeLinker: pnp

packageExtensions:
  "@babel/plugin-transform-react-jsx@*":
    dependencies:
      "@babel/core": "*"
  "@babel/preset-env@*":
    dependencies:
      "@babel/core": "*"
  "@mdx-js/react@*":
    dependencies:
      react: "*"
  "@storybook/addon-measure@*":
    dependencies:
      "@storybook/components": "*"
      "@storybook/core-events": "*"
      "@storybook/theming": "*"
  "@storybook/core-client@*":
    dependencies:
      webpack: "*"
  babel-loader@*:
    dependencies:
      webpack: "*"
  css-loader@*:
    dependencies:
      webpack: "*"
  eslint-config-airbnb-base@*:
    dependencies:
      eslint: "*"
      eslint-plugin-import: "*"
  fork-ts-checker-webpack-plugin@*:
    dependencies:
      typescript: "*"
      webpack: "*"
  sass-loader@*:
    dependencies:
      webpack: "*"
  style-loader@*:
    dependencies:
      webpack: "*"
  react-server-dom-webpack@*:
    dependencies:
      webpack: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

yarnPath: .yarn/releases/yarn-berry.cjs

changesetBaseRefs: ["main"]
